### PR TITLE
Add star rating functionality

### PR DESCRIPTION
**Pull request by matthewtlam**

### CODE REVIEW

**Review by perrycate — APPROVED** [review]

**Comment by perrycate** [comment]
I noticed this PR is to merge it into master of your own repository. For next time, I think you should be able to make the pull request into master of the shared group repository.

EDIT: Ignore me, I'm wrong. This PR is definitely merging into master of the project repo.

**Comment by Mmendero** [comment]
Hey! There are merge conflicts within the files pushed in this pull request with the files I just merged in my first pull request. The affected files are:
- ...webapp/index.html
- ...webapp/script.js.

Would you be able to pull the changes from the new master repository then add the changes you've made?

**Comment by perrycate** [comment]
Let me know if y'all need help resolving merge conflicts - I know it's been a while since we talked about them.

**Review by Mmendero — APPROVED** [review]
Everything Looks good!

**Pull request merged**
